export const radarChartData = [
  {
    "Financial Health": [
      {
        indicatorName: "Current Ratio",
        "Retail Banking": 90,
        "Commercial Banking": 75,
        "Investment Banking": 95,
        "Wealth Management": 80,
        "Asset Management": 85,
      },
      {
        indicatorName: "Net Profit Margin",
        "Retail Banking": 75,
        "Commercial Banking": 90,
        "Investment Banking": 95,
        "Wealth Management": 80,
        "Asset Management": 85,
      },
      {
        indicatorName: "Debt to Equity",
        "Retail Banking": 80,
        "Commercial Banking": 70,
        "Investment Banking": 60,
        "Wealth Management": 85,
        "Asset Management": 90,
      },
      {
        indicatorName: "Loan to Deposit Ratio",
        "Retail Banking": 90,
        "Commercial Banking": 95,
        "Investment Banking": 70,
        "Wealth Management": 85,
        "Asset Management": 50,
      },
      {
        indicatorName: "Cost to Income Ratio",
        "Retail Banking": 55,
        "Commercial Banking": 60,
        "Investment Banking": 50,
        "Wealth Management": 45,
        "Asset Management": 40,
      },
    ],
    "Operational Efficiency": [
      {
        indicatorName: "Asset Turnover",
        "Retail Banking": 70,
        "Commercial Banking": 60,
        "Investment Banking": 90,
        "Wealth Management": 80,
        "Asset Management": 100,
      },
      {
        indicatorName: "Return on Assets",
        "Retail Banking": 60,
        "Commercial Banking": 75,
        "Investment Banking": 100,
        "Wealth Management": 90,
        "Asset Management": 80,
      },
      {
        indicatorName: "Operational Efficiency Ratio",
        "Retail Banking": 65,
        "Commercial Banking": 60,
        "Investment Banking": 55,
        "Wealth Management": 50,
        "Asset Management": 45,
      },
      {
        indicatorName: "Non-Interest Expense to Average Assets",
        "Retail Banking": 75,
        "Commercial Banking": 70,
        "Investment Banking": 85,
        "Wealth Management": 90,
        "Asset Management": 95,
      },
      {
        indicatorName: "Interest Income to Total Income",
        "Retail Banking": 60,
        "Commercial Banking": 65,
        "Investment Banking": 55,
        "Wealth Management": 70,
        "Asset Management": 75,
      },
    ],
  },
];
