import { Inter } from "next/font/google";
import "./globals.css";
import { Button, ConfigProvider as AntDesignConfigProvider, Space } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cockpit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntDesignConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#006eff",
              borderRadius: 2,

              // Alias Token
              colorBgContainer: "#ffffff",
            },
          }}
        >
          {children}
        </AntDesignConfigProvider>
      </body>
    </html>
  );
}
